server:
  port: 8070

spring:
  application:
    name: inventory-tracking-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryserver
    username: root
    password: Bannu@123
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8661/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
        
  