server:
  port: 8080

spring:
  application:
    name: inventory-tracking-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryserver?createDatabaseIfNotExist=true
    username: root
    password: Bannu@123
    driver-class-name: com.mysql.cj.jdbc.Driver   
  

    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'