server:
  port: 8072

spring:
  application:
    name: stockReplenishmentService
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/stockService
    username: root
    password: Bannu@123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8661/eureka
    registerWithEureka: true
    fetchRegistry: true
 