spring:
  application:
    name: eureka-server
  profiles:
    active: default 
server:
  port: 8661

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8661/eureka
      
  instance:
    hostname: localhost
