server:
  port: 8083

spring:
  application:
    name: supplierManagementService
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/supplierserver?createDatabaseIfNotExist=true
    username: root
    password: Bannu@123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true